version = 0.1
[default.deploy.parameters]
stack_name = "documentai"
resolve_s3 = true
s3_prefix = "documentai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []